apiVersion: v1
kind: Deployment
metadata:
  name: cookie-serve
  labels:
    app: cookie-serve
spec: 
  selector:
    matchLabels:
      app: cookie-serve
  template:
    metadata:
      labels:
        app: cookie-serve
    spec:
      containers:
        - name: cookie-serve
          image: lilybw/sdu-s10-cicd-fortuna:backend-latest
          env:
            - name: SERVE_COOKIE
              value: "true"