apiVersion: apps/v1
kind: Service
metadata:
  name: cookie-serve-service
  labels:
    app: cookie-serve
spec:
  type: NodePort
  selector:
    app: cookie-serve
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000