apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: student-12
  labels:
    app: cookie-serve-frontend
spec:
  type: NodePort
  selector:
    app: cookie-serve-frontend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080