apiVersion: v1
kind: Service
metadata:
  name: cookie-serve-backend
  namespace: student-12
  labels:
    app: cookie-serve-backend
spec:
  type: ClusterIP
  selector:
    app: cookie-serve-backend
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000